
plugins:
  - serverless-offline-python
  - serverless-apigw-binary


service: caligraf-audio-converter # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1
  memorySize: 512
  # profile: serverless

functions:
  converter:
    handler: handler.converter
    events:
      - http:
          path: convert
          method: post
          cors: true
